manual config first run

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,31 +4,63 @@ jobs:
     docker:
       - image: docker:17.05.0-ce-git
     steps:
-      # required to run multiple containers
-      - setup_remote_docker
       # check out our code
       - checkout
 
-      - run:
-          name: Build my application
-          # build our app and call it 
-          command: |
-            docker build -t my-app:0.1.$CIRCLE_BUILD_NUM .
+      # - run:
+      #     name: Install dependencies, etc
+      #     command: npm install .
+
+      # - run:
+      #     name: Start application
+      #     command: node server.js
+      #     background: true
+
 
       - run:
           name: Execute test
           command: |
-            docker network create temp-network
-            docker run -d \
-              --network temp-network \
-              --name my-app \
-              my-app:0.1.$CIRCLE_BUILD_NUM --sha=$CIRCLE_SHA1
-
-            docker run \
-              -e APP_PORT=my-app:$APP_PORT \
-              -e GI_API_KEY=$GI_API_KEY \
-              -e GI_SUITE=$GI_SUITE \
-              -e NGROK_TOKEN=$NGROK_TOKEN \
-              --network temp-network \
-              ghostinspector/test-runner-standalone
+            # Tailor this command to suit your application, *must* have the trailing '&'
+            node server.js &
+            # Download ngrok and unzip
+            wget -qN https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
+            unzip ngrok-stable-linux-amd64.zip
+            chmod +x ngrok
+            # Download JSON parser for determining ngrok tunnel
+            wget -qN -Ojq https://stedolan.github.io/jq/download/linux64/jq
+            chmod +x jq
+            # Intialize ngrok and open tunnel to our application
+            ./ngrok authtoken $NGROK_TOKEN
+            ./ngrok http $APP_PORT > /dev/null &
+            # give ngrok a second to register URLs
+            sleep 5
+            # Grab the ngrok url to send to the API
+            START_URL=$(curl -s 'http://localhost:4040/api/tunnels' | ./jq -r '.tunnels[1].public_url')
+            echo "Using start URL: $START_URL"
+            # Set up a couple variables to monitor result state
+            STATUS='null'
+            SUITE_RESULT=
+            PASSING=
+            # Execute Ghost Inspector suite via API and grab the result ID
+            EXECUTE_URL="https://api.ghostinspector.com/v1/suites/$GI_SUITE/execute/?apiKey=$GI_API_KEY&startUrl=$START_URL&immediate=1"
+            echo "Executing suite: $EXECUTE_URL"
+            RESULT_ID=$(curl -s $EXECUTE_URL | ./jq -r '.data._id')
+            # for the suite result, sleep for a few seconds if it hasn't changed
+            echo "Polling for suite results (ID: $RESULT_ID)"
+            while [ "$STATUS" = 'null' ]; do
+              sleep 5
+              SUITE_RESULT=$(curl -s "https://api.ghostinspector.com/v1/suite-results/$RESULT_ID/?apiKey=$API_KEY")
+              STATUS=$(echo $SUITE_RESULT | ./jq -r '.data.passing')
+              echo " - status: $STATUS"
+            done
+            # status has been updated, check results for "passing"
+            if [ "$(echo $SUITE_RESULT | ./jq -r '.data.passing')" != 'true' ]; then
+              echo "Suite failed! ¯\_(ツ)_/¯"
+              PASSING=1
+            else 
+              echo "Suite passed! \o/"
+              PASSING=0
+            fi
+            # return our passing status
+            exit $PASSING
             
